---
- name: Install webserver 
  hosts: webserver
  tasks:
    - name: Install httpd package is present
      yum:
        name: httpd
        state: present
      
    - name: Install index.html in web servers
      copy:
        src: /tmp/index.html
        dest: /var/www/html/index.html
        force: true
    
    - name: check firewalld service is running
      service:
        name: firewalld
        state: started
        enabled: true

    - name: firewald permits access to httpd service
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: httpd enable and running
      service:
        name: httpd
        state: started
        enabled: true

- name: Test web server
  hosts: localhost
  become: no
  tasks:
    - name: connect to web server
      uri:
        url: http://192.168.56.110
        return_content: yes
        status_code: 200

